apiVersion: v1
kind: Service
metadata:
  name: reseller-mgmt
  namespace: billing-demo
spec:
  type: NodePort
  selector:
    app: reseller-mgmt
  ports:
    - port: 8808
      protocol: TCP
      targetPort: 8808
      nodePort: 32118 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reseller-mgmt-pod-depolyment
  namespace: billing-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: reseller-mgmt
  template:
    metadata:
      labels:
        app: reseller-mgmt
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: efs-claim-1
      containers:
        - name: reseller-mgmt-container
          image:  hariprasadreddypitta/docker-repository:reseller_mgmt
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8808
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"

