apiVersion: v1
kind: Service
metadata:
  name: infimobile-static
  namespace: billing-demo
spec:
  type: NodePort
  selector:
    app: infimobile-static
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32144
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infimobile-static-pod-depolyment
  namespace: billing-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: infimobile-static
  template:
    metadata:
      labels:
        app: infimobile-static
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: efs-claim-1
      containers:
        - name: infimobile-static-container
          image:  hariprasadreddypitta/docker-repository:infimobile_static
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8080
          volumeMounts:
                  - name: efs-pvc
                    mountPath: /usr/local/tomcat/webapps/ROOT/fetch_documents

