apiVersion: v1
kind: Service
metadata:
  name: catlmgmt-svc
  namespace: billing-demo
spec:
  type: NodePort
  selector:
    app: catlmgmt
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
      nodePort: 32184
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catlmgmt-pod-deployment
  namespace: billing-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: catlmgmt
  template:
    metadata:
      labels:
        app: catlmgmt
    spec:
      containers:
        - name: catlmgmt-container
          image:  hariprasadreddypitta/docker-repository:ctlg_mgmt
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
          - containerPort: 8084
