apiVersion: v1
kind: Service
metadata:
  name: billingreports
  namespace: billing-demo
spec:
  type: NodePort
  selector:
    app: billingreports
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
      nodePort: 32116 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingreports-pod-depolyment
  namespace: billing-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: billingreports
  template:
    metadata:
      labels:
        app: billingreports
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: efs-claim-1
      containers:
        - name: billing-reports-container
          image:  hariprasadreddypitta/docker-repository:billing_reports
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8091
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"
