apiVersion: v1
kind: Service
metadata:
  name: integration
  namespace: billing-demo
spec:
  type: NodePort
  selector:
    app: integration
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
      nodePort: 32101 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-pod-depolyment
  namespace: billing-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      labels:
        app: integration
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: efs-claim-1
#              - name: emailjson
#                nfs:
#                        server: 172.21.16.42
#                        path:  /mnt/central_documents/email_template_json
      containers:
        - name: integration-container
          image:  hariprasadreddypitta/docker-repository:billing_integ
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8090
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"
#                  - name: emailjson
#                    mountPath: /opt/email_template_json 
