
apiVersion: v1
kind: Service
metadata:
  name: invt-mgmt-service
  namespace: billing-demo
spec:
  type: NodePort
  selector:
    app: invt_mgmt
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 32103 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invt-mgmt-pod-depolyment
  namespace: billing-demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: invt_mgmt
  template:
    metadata:
      labels:
        app: invt_mgmt
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: efs-claim-1
      containers:
        - name: invt-mgmt-container
          image:  hariprasadreddypitta/docker-repository:invt_mgmt
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8083
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"

