apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvccc
  namespace: billing-demo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi

