kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummy-run-nfs-client-provisioner
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner
  namespace: dummy
roleRef:
  kind: ClusterRole
  name: dummy-nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
