apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvvv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummyefs
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: REPLACE_WITH_ID


