kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dummy
  name: leader-locking-nfs-client-provisioner
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner
  namespace: dummy
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io
