apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: redis
                      
        volumeMounts:
        - name: anyname
          mountPath: "/data"
      volumes:
      - name: anyname
        persistentVolumeClaim:
          claimName: pvccc
