kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-provisioner
subjects:
- kind: ServiceAccount
  name: config-provisioner
  namespace: billing-demo
roleRef:
  kind: ClusterRole
  name: config-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
