apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: billing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: redis
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-pv
          mountPath: "/opt/config-properties"
      volumes:
      - name: config-pv
        persistentVolumeClaim:
          claimName: config-pvc
