
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: config-efs
  mountOptions:
    - vers=4.1
  nfs:
    path: "/mnt/config_properties"
    server: 172.28.28.143
