kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-provisioner-role
  namespace: billing-demo
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
