kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: billing-demo
  name: config-provisioner
subjects:
- kind: ServiceAccount
  name: config-provisioner
  namespace: billing-demo
roleRef:
  kind: Role
  name: config-provisioner-role
  apiGroup: rbac.authorization.k8s.io
