apiVersion: v1
kind: Service
metadata:
  name: mno-mgmt
  namespace: test-infimobile
spec:
  type: NodePort
  selector:
    app: mno-mgmt
  ports:
    - port: 8807
      protocol: TCP
      targetPort: 8807
      nodePort: 32113
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mno-mgmt-pod-depolyment
  namespace: test-infimobile
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: mno-mgmt
  template:
    metadata:
      labels:
        app: mno-mgmt
    spec:
      volumes:
              - name: documents
                persistentVolumeClaim:
                        claimName: nfs-pvc-document
      containers:
        - name: mno-mgmt-container
          image:  dockerregistry.infimobile.com:5000/mno_mgmt:latest
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8807
          volumeMounts:
                  - name: documents
                    mountPath: /opt/documents_root

