apiVersion: v1
kind: Service
metadata:
  name: invt-mgmt-service
  namespace: test-infimobile
spec:
  type: NodePort
  selector:
    app: invt_mgmt
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 32103 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invt-mgmt-pod-depolyment
  namespace: test-infimobile
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: invt_mgmt
  template:
    metadata:
      labels:
        app: invt_mgmt
    spec:
      volumes:
              - name: documents
                persistentVolumeClaim:
                        claimName: nfs-pvc-document
      containers:
        - name: invt-mgmt-container
          image:  dockerregistry.infimobile.com:5000/invt_mgmt:latest
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8083
          volumeMounts:
                  - name: documents
                    mountPath: /opt/documents_root

