apiVersion: v1
kind: Service
metadata:
  name: infimobile-website
  namespace: test-infimobile
spec:
  type: NodePort
  selector:
    app: infimobile-website
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infimobile-website-pod-depolyment
  namespace: test-infimobile
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: infimobile-website
  template:
    metadata:
      labels:
        app: infimobile-website
    spec:
      volumes:
              - name: documents
                persistentVolumeClaim:
                        claimName: nfs-pvc-document
      containers:
        - name: infimobile-website-container
          image:  dockerregistry.infimobile.com:5000/gorilla_static:latest
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8080
          volumeMounts:
                  - name: documents
                    mountPath: /opt/documents_root

