apiVersion: v1
kind: Service
metadata:
  name: prrcollector-server
  namespace: test-infimobile
spec:
  type: NodePort
  selector:
    app: prrcollector
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 32122
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prrcollector-deployment
  namespace: test-infimobile
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: prrcollector
  template:
    metadata:
      labels:
        app: prrcollector
    spec:
      containers:
        - name: prrcollecctor-container
          image: dockerregistry.infimobile.com:5000/prrcollector_mgmt:latest
          imagePullPolicy: Always
          resources:
            requests:
                    cpu: "500m"
            limits:
                    memory: "1512Mi"
                    cpu: "2000m"
          ports:
          - containerPort: 9000
          volumeMounts:
                  - name: prr-files
                    mountPath: /opt/prr
      volumes:
              - name: prr-files
                nfs:
                        server: 172.21.16.42
                        path: /mnt/prr
