apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: test-infimobile
spec:
  type: NodePort
  selector:
    app: integration
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
      nodePort: 32101 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-deployment
  namespace: test-infimobile
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      labels:
        app: integration
    spec:
      containers:
        - name: integration-container
          image:  dockerregistry.infimobile.com:5000/billing_integ:latest
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
          - containerPort: 8090
          env:
          - name: billingrepo
            valueFrom: 
             configMapKeyRef:
               name: mysql-config
               key: billingrepo
          - name: cataloguemgmtrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: cataloguemgmtrepo
          - name: ejabberdrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: ejabberdrepo
          - name: inventorymgmtrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: inventorymgmtrepo
          - name: mnoplanrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mnoplanrepo
          - name: servicemgmtrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: servicemgmtrepo
          - name: shipmentmanagementrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: shipmentmanagementrepo
          - name: sspaymentrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key:  sspaymentrepo
          - name: taxmgmtrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: taxmgmtrepo
          - name: userkycrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: userkycrepo
          - name: walletmgmtrepo
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: walletmgmtrepo
          - name: mqttbroker
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mqttbroker

          - name: config-hub
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: config-hub

