apiVersion: v1
kind: Service
metadata:
  name: tax-mgmt
  namespace: test-infimobile
spec:
  type: NodePort
  selector:
    app: tax-mgmt
  ports:
    - port: 8097
      protocol: TCP
      targetPort: 8097
      nodePort: 32110 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-mgmt-pod-depolyment
  namespace: test-infimobile
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: tax-mgmt
  template:
    metadata:
      labels:
        app: tax-mgmt
    spec:
      volumes:
              - name: documents
                persistentVolumeClaim:
                        claimName: nfs-pvc-document
      containers:
        - name: tax-mgmt-container
          image:  dockerregistry.infimobile.com:5000/tax_mgmt:latest
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8097
          volumeMounts:
                  - name: documents
                    mountPath: /opt/documents_root

