---
apiVersion: v1
kind: Service
metadata:
  name: mqttbroker
  namespace: test-infimobile
spec:
  selector:
    app: mqttbroker
  ports:
  - port: 1883
    targetPort: 1883

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: test-infimobile
spec:
  selector:
    matchLabels:
      app: mqttbroker
  template:
    metadata:
      labels:
        app: mqttbroker
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1883
        volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
