apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: read-write-binding
 namespace: test-infimobile
roleRef:
 kind: Role
 name: read-write
 apiGroup: rbac.authorization.k8s.io
subjects:
        - kind: User
          name: test-infimobile
          apiGroup: rbac.authorization.k8s.io
