apiVersion: v1
kind: Service
metadata:
  name: cdrmgmt-server
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: cdrmgmt
  ports:
    - port: 8989
      protocol: TCP
      targetPort: 8989
      nodePort: 32112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr-deployment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: cdrmgmt
  template:
    metadata:
      labels:
        app: cdrmgmt
    spec:
      containers:
        - name: cdrmgmt-container
          image: infimobile/docker:cdr_mgmt
          imagePullPolicy: Always
          resources:
            requests:
                    cpu: "500m"
            limits:
                    memory: "1512Mi"
                    cpu: "2000m"
          ports:
          - containerPort: 8989
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/prr"
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      imagePullSecrets:
        - name: infimobile-dockerhub-secret           
#        nfs:
#                        server: 172.21.16.42
#                        path: /mnt/prr
