apiVersion: v1
kind: Service
metadata:
  name: tax-mgmt
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: tax-mgmt
  ports:
    - port: 8097
      protocol: TCP
      targetPort: 8097
      nodePort: 32110 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-mgmt-pod-depolyment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: tax-mgmt
  template:
    metadata:
      labels:
        app: tax-mgmt
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      containers:
        - name: tax-mgmt-container
          image:  infimobile/docker:tax_mgmt
#          command: ["/bin/sh"]
#          args: ["-c", "while true; do echo hello; sleep 10;done"]
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8097
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"
      imagePullSecrets:
        - name: infimobile-dockerhub-secret
