apiVersion: v1
kind: Service
metadata:
  name: self-service-payment
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: self-mgmt
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
      nodePort: 32105 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-mgmt-pod-depolyment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: self-mgmt
  template:
    metadata:
      labels:
        app: self-mgmt
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      containers:
        - name: self-mgmt-container
          image:  infimobile/docker:self_mgmt
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"

          ports:
                  - containerPort: 8086
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "opt/documents_root"
      imagePullSecrets:
        - name: infimobile-dockerhub-secret
