apiVersion: v1
kind: Service
metadata:
  name: apisecurity-service
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: apisecurity
  ports:
    - port: 9009
      protocol: TCP
      targetPort: 9009
      nodePort: 32129
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisecurity-pod-depolyment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: apisecurity
  template:
    metadata:
      labels:
        app: apisecurity
    spec:
      containers:
        - name: apisecurity-container
          image:  infimobile/docker:api_security
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 9009
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/test/"
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      imagePullSecrets:
        - name: infimobile-dockerhub-secret                  
#                nfs:
#                        server: 172.21.16.42
#                        path: /mnt/test
