apiVersion: v1
kind: Service
metadata:
  name: service-mgmt
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: service-mgmt
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 32106
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mgmt-pod-depolyment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: service-mgmt
  template:
    metadata:
      labels:
        app: service-mgmt
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      containers:
        - name: service-mgmt-container
          image:  infimobile/docker:service_mgmt
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8085
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"

      imagePullSecrets:
        - name: infimobile-dockerhub-secret
