apiVersion: v1
kind: Service
metadata:
  name: infimobile-reseller-dash
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: infimobile-reseller-dash
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32146
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infimobile-reseller-dash-pod-depolyment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 
  selector:
    matchLabels:
      app: infimobile-reseller-dash
  template:
    metadata:
      labels:
        app: infimobile-reseller-dash
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      containers:
        - name: infimobile-reseller-dash-container
          image:  infimobile/docker:reseller_dashboard
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 8080
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"
      imagePullSecrets:
        - name: infimobile-dockerhub-secret
