apiVersion: v1
kind: Service
metadata:
  name: infimobile-validation
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: infimobile-validation
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 32090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infimobile-validation-pod-depolyment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: infimobile-validation
  template:
    metadata:
      labels:
        app: infimobile-validation
    spec:
      volumes:
              - name: efs-pvc
                persistentVolumeClaim:
                        claimName: pvccc
      containers:
        - name: infimobile-validation-container
          image:  infimobile/docker:infimobile_validation
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
                    memory: "2048Mi"
                    cpu: "2000m"
          ports:
                  - containerPort: 9090
          volumeMounts:
                  - name: efs-pvc
                    mountPath: "/opt/documents_root"
      imagePullSecrets:
        - name: infimobile-dockerhub-secret              
