kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-stage-document-provisioner
subjects:
- kind: ServiceAccount
  name: nfs-stage-document-provisioner
  namespace: stage-env
roleRef:
  kind: ClusterRole
  name: nfs-stage-document-provisioner
  apiGroup: rbac.authorization.k8s.io
