apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-stage-document-provisioner
  namespace: stage-env
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-stage-document-provisioner
  template:
    metadata:
      labels:
        app: nfs-stage-document-provisioner
    spec:
      serviceAccountName: nfs-stage-document-provisioner
      containers:
        - name: nfs-stage-document-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-stage-document-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 172.21.16.42
            - name: NFS_PATH
              value: /mnt/central_documents
      volumes:
        - name: nfs-stage-document-root
          nfs:
            server: 172.21.16.42
            path: /mnt/central_documents

