apiVersion: v1
kind: Service
metadata:
  name: config-hub
  namespace: dummy
spec:
  type: NodePort
  selector:
    app: configserver
  ports:
    - port: 8094
      protocol: TCP
      targetPort: 8094
      nodePort: 30194
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: dummy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver-container
          image: infimobile/docker:config_server
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 8094
          volumeMounts:
            - name: efs-pvc
              mountPath: "/opt/config_server/"
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: pvccc
      imagePullSecrets:
        - name: infimobile-dockerhub-secret        
            
            
