apiVersion: v1
kind: Service
metadata:
  name: config-hub
  namespace: stage-env
spec:
  selector:
    app: configserver
  ports:
    - port: 8094
      protocol: TCP
      targetPort: 8094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: stage-env
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver-container
          image: dockerregistry.infimobile.com:4000/config_server:latest
          imagePullPolicy: Always
          resources:
            requests:
                    cpu: "50m"
            limits:
                    memory: "512Mi"
                    cpu: "200m"
          ports:
          - containerPort: 8094
          volumeMounts:
                  - name: config
                    mountPath: /opt/config_server/
      volumes:
              - name: config
                nfs:
                        server: 172.21.16.42
                        path: /mnt/config_properties/

